#!/usr/bin/env bash
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
    SOURCE="$(readlink "$SOURCE")"
      [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
      done
      DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
if [ -z "$1" ]; then
   java -Dapi.port=8080 -Dapi.mode=”production” -jar "$DIR/../bgeapi-assembly-1.0.jar"
else
   java -Dapi.port=$1 -Dapi.mode=”production” -jar "$DIR/../bgeapi-assembly-1.0.jar"
fi   

